### ISSUE TITLE
LC3Tools should not ignore commas

### ISSUE THREAD

**Issue by ausbin** [gt-cs2110/lc3tools#8]
Currently, you can write stuff like `NOT R3 R3` or even `NOT R3,,,,,,,,,,,R3` and LC3Tools doesn't care. We should make it more strict about this, because students are writing things like `NOT R3 R3` on quizzes and homeworks

**Comment by richardso21** [comment]
Lmao
https://github.com/gt-cs2110/lc3tools/blob/2622c49cd12478adde3ebe60b2a3a73e11a298f5/src/backend/tokenizer.cpp#L93-L98

**Comment by richardso21** [comment]
Figured out a fix for this, will make a PR for this and some other fixes in the near future
